import { normalizeRoleKey } from "@/lib/roleKeyUtils";

/**
 * Default module_access keys per role — used when rep_list.module_access is NULL
 * (legacy users never configured via Quick Edit / Global Module Access).
 * Keep in sync with admin Employees → Global Module Access defaults.
 */
export const ROLE_DEFAULT_MODULE_KEYS = {
  SALES: [
    "dashboard-home",
    "task-manager",
    "fast-card",
    "view-customers",
    "add-customer",
    "daily-report",
    "lead-reports",
    "demo-details",
    "quotations",
    "orders-process",
    "product-stock",
    "expenses",
    "employee-crm",
    "prospects-view",
    "prospects-add",
    "installation-videos",
  ],
  "SALES HEAD": [
    "dashboard-home",
    "task-manager",
    "fast-card",
    "view-customers",
    "add-customer",
    "my-leads",
    "daily-report",
    "lead-reports",
    "demo-details",
    "customer-payment-behavior",
    "quotations",
    "orders-process",
    "orders-delay",
    "schedule-visits",
    "tl-customers",
    "product-stock",
    "expenses",
    "payment-pending",
    "employee-crm",
    "prospects-view",
    "prospects-add",
    "sales-target",
    "installation-videos",
    "denied-leads",
  ],
  ADMIN: [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "daily-report",
    "lead-reports",
    "view-customers",
    "add-customer",
    "my-leads",
    "quotations",
    "orders-process",
    "orders-delay",
    "payment-pending",
    "expenses",
    "view-expenses",
    "employee-list",
    "employee-crm",
    "product-stock",
    "spare-parts",
    "tl-customers",
    "attendance-log",
  ],
  "BACK OFFICE": [
    "dashboard-home",
    "task-manager",
    "view-customers",
    "add-customer",
    "quotations",
    "orders-process",
    "orders-delay",
    "product-stock",
    "payment-pending",
    "employee-crm",
    "daily-report",
    "installation-videos",
  ],
  "WAREHOUSE INCHARGE": [
    "dashboard-home",
    "task-manager",
    "employee-crm",
    "view-customers",
    "product-stock",
    "product-accessories",
    "spare-parts",
    "purchase-direct-in",
    "purchase-request",
    "purchase-warehouse-in",
    "purchases",
    "purchase-ledger",
    "spare-direct-in",
    "spare-request",
    "spare-warehouse-in",
    "spare-purchases",
    "production-status",
    "bom-list",
  ],
  WELDER: [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "employee-crm",
  ],
  "WELDER HELPER": [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "employee-crm",
  ],
  ACCOUNTANT: [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "view-customers",
    "add-customer",
    "daily-report",
    "demo-details",
    "quotations",
    "orders-process",
    "invoices",
    "product-stock",
    "product-accessories",
    "spare-parts",
    "purchase-direct-in",
    "purchase-request",
    "purchase-warehouse-in",
    "purchases",
    "spare-direct-in",
    "spare-request",
    "spare-warehouse-in",
    "spare-purchases",
    "payment-pending",
    "manual-payments",
    "expenses",
    "view-expenses",
    "dd-management",
    "other-income",
    "bank-management",
    "client-expenses",
    "delivery-challan",
    "statements",
    "salary-slips",
    "employee-crm",
    "company-documents",
    "assets",
    "attendance-log",
  ],
  "TEAM LEADER": [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "view-customers",
    "add-customer",
    "my-leads",
    "daily-report",
    "customer-payment-behavior",
    "leads-upload",
    "denied-leads",
    "warranty-console",
    "registered-products",
    "service-followups",
    "warranty-map",
    "service-records",
    "upcoming-installations",
    "service-map",
    "payment-pending",
    "employee-crm",
  ],
  "DIGITAL MARKETER": [
    "dashboard-home",
    "task-manager",
    "view-customers",
    "my-leads",
    "leads-upload",
    "keywords-management",
    "backlinks-management",
    "meta-credentials-add",
    "daily-report",
    "blog",
    "employee-crm",
  ],
  HR: [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "salary-slips",
    "employee-list",
    "employee-crm",
    "hiring-process",
    "hr-daily-report",
    "attendance-log",
  ],
  "HR HEAD": [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "salary-slips",
    "employee-list",
    "employee-crm",
    "hiring-process",
    "hr-daily-report",
    "attendance-log",
  ],
  "JUNIOR HR EXECUTIVE": [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "salary-slips",
    "employee-list",
    "employee-crm",
    "hiring-process",
    "hr-daily-report",
    "attendance-log",
  ],
  "HR EXECUTIVE": [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "salary-slips",
    "employee-list",
    "employee-crm",
    "hiring-process",
    "hr-daily-report",
    "attendance-log",
  ],
  "HR RECRUITER": [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "salary-slips",
    "employee-list",
    "employee-crm",
    "hiring-process",
    "hr-daily-report",
    "attendance-log",
  ],
  GEM: [
    "dashboard-home",
    "task-manager",
    "add-customer",
    "view-customers",
    "quotations",
    "orders-process",
    "payment-pending",
    "dd-management",
    "employee-crm",
    "gem-crm-dashboard",
    "gem-crm-bids",
    "gem-crm-reports",
    "installation-videos",
  ],
  "GEM PORTAL": [
    "dashboard-home",
    "task-manager",
    "add-customer",
    "view-customers",
    "quotations",
    "orders-process",
    "payment-pending",
    "dd-management",
    "employee-crm",
    "gem-crm-dashboard",
    "gem-crm-bids",
    "gem-crm-reports",
    "installation-videos",
  ],
  "GRAPHIC DESIGNER": [
    "dashboard-home",
    "task-manager",
    "daily-report",
    "employee-crm",
    "installation-videos",
    "installation-videos-manage",
    "assets",
  ],
  "DESIGN ENGINEER": [
    "dashboard-home",
    "task-manager",
    "spare-parts",
    "spare-direct-in",
    "spare-request",
    "spare-warehouse-in",
    "spare-purchases",
    "production-status",
    "bom-list",
    "expenses",
    "employee-crm",
  ],
  "PRODUCTION ENGINEER": [
    "dashboard-home",
    "task-manager",
    "employee-crm",
  ],
  "MACHINE OPERATOR": [
    "dashboard-home",
    "task-manager",
    "employee-crm",
  ],
  DEVELOPER: [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "employee-crm",
  ],
  "SERVICE ENGINEER": [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "employee-crm",
  ],
  "SERVICE TECHNICIAN": [
    "dashboard-home",
    "task-manager",
    "regularization-approvals",
    "employee-crm",
  ],
  "SERVICE HEAD": [
    "dashboard-home",
    "task-manager",
    "add-customer",
    "view-customers",
    "employee-crm",
    "quotations",
    "orders-process",
    "orders-delay",
    "warranty-console",
    "registered-products",
    "service-followups",
    "warranty-map",
    "service-records",
    "upcoming-installations",
    "service-map",
    "product-stock",
    "spare-parts",
    "installation-videos",
    "return-products",
  ],
  "SERVICE SUPPORT": [
    "dashboard-home",
    "task-manager",
    "add-customer",
    "view-customers",
    "employee-crm",
    "quotations",
    "orders-process",
    "orders-delay",
    "warranty-console",
    "registered-products",
    "service-followups",
    "warranty-map",
    "service-records",
    "upcoming-installations",
    "service-map",
    "product-stock",
    "spare-parts",
    "installation-videos",
    "return-products",
  ],
  "SALES CUM BACKOFFICE": [
    "dashboard-home",
    "daily-report",
    "add-customer",
    "view-customers",
    "my-leads",
    "bulk-reassign",
    "denied-leads",
    "task-manager",
    "fast-card",
    "quotations",
    "orders-process",
    "product-stock",
    "spare-parts",
    "payment-pending",
    "manual-payments",
    "employee-crm",
    "prospects-add",
    "prospects-ne",
    "installation-videos",
  ],
  DIRECTOR: [
    "dashboard-home",
    "daily-report",
    "lead-reports",
    "quotations-report",
    "order-report",
    "demo-followups",
    "item-wise-sales",
    "customer-payment-behavior",
    "lead-distribution",
    "orders-process",
    "orders-delay",
    "estimate-delivery",
    "bulk-reassign",
    "my-leads",
    "dm-fresh-leads",
    "task-manager",
    "demo-details",
    "attendance-details",
    "regularization-approvals",
    "fast-card",
    "schedule-visits",
    "tl-customers",
    "add-customer",
    "view-customers",
    "quotations",
    "invoices",
    "ads-management",
    "keywords-management",
    "backlinks-management",
    "backlinks-excel-data",
    "meta-credentials-add",
    "leads-upload",
    "denied-leads",
    "prospects-view",
    "prospects-add",
    "prospects-new",
    "hr-designation-targets",
    "sales-target",
    "warranty-console",
    "registered-products",
    "service-followups",
    "warranty-map",
    "service-records",
    "upcoming-installations",
    "service-map",
    "amc-cmc",
    "return-products",
    "product-stock",
    "product-accessories",
    "purchase-direct-in",
    "purchase-request",
    "purchase-warehouse-in",
    "purchases",
    "purchase-ledger",
    "spare-parts",
    "spare-direct-in",
    "spare-request",
    "spare-warehouse-in",
    "spare-purchases",
    "production-status",
    "bom-list",
    "employee-list",
    "employee-crm",
    "attendance-log",
    "payment-pending",
    "manual-payments",
    "expenses",
    "view-expenses",
    "dd-management",
    "other-income",
    "import-billing",
    "ledger",
    "bank-management",
    "client-expenses",
    "delivery-challan",
    "statements",
    "salary-slips",
    "company-documents",
    "blog",
    "qa-approval",
    "qa",
    "email-templates",
    "holidays",
    "installation-videos",
    "installation-videos-manage",
    "assets",
    "import-agents",
    "import-suppliers",
    "import-shipments",
    "import-quote-submissions",
    "import-award-followups",
    "gem-crm-dashboard",
    "gem-crm-bids",
    "gem-crm-reports",
    "attendance-rules",
    "hiring-process",
    "final-profile-approval",
    "hr-daily-report",
  ],
};

/** Role presets for users whose module_access column is still NULL. */
export function getRoleDefaultModuleKeys(role) {
  const key = normalizeRoleKey(role);
  if (!key) return [];

  const exact = ROLE_DEFAULT_MODULE_KEYS[key];
  if (exact?.length) return [...exact];

  // Specific roles before broad substring fallbacks (order matters)
  if (key.includes("SALES HEAD") || key === "SALES_HEAD") {
    const preset = ROLE_DEFAULT_MODULE_KEYS["SALES HEAD"];
    return preset?.length ? [...preset] : [...(ROLE_DEFAULT_MODULE_KEYS.SALES ?? [])];
  }
  if (key.includes("SALES")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS.SALES ?? [])];
  }
  if (key.includes("SERVICE HEAD")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["SERVICE HEAD"] ?? [])];
  }
  if (key.includes("SERVICE SUPPORT")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["SERVICE SUPPORT"] ?? [])];
  }
  if (key.includes("SERVICE ENGINEER")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["SERVICE ENGINEER"] ?? [])];
  }
  if (key.includes("SERVICE TECHNICIAN")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["SERVICE TECHNICIAN"] ?? [])];
  }
  if (key.includes("WAREHOUSE")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["WAREHOUSE INCHARGE"] ?? [])];
  }
  if (key.includes("ACCOUNTANT")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS.ACCOUNTANT ?? [])];
  }
  if (key.includes("HR")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS.HR ?? [])];
  }
  if (key.includes("GEM")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS.GEM ?? [])];
  }
  if (key.includes("MARKETER") || key.includes("DIGITAL")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["DIGITAL MARKETER"] ?? [])];
  }
  if (key.includes("DESIGN ENGINEER")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["DESIGN ENGINEER"] ?? [])];
  }
  if (key.includes("PRODUCTION ENGINEER")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["PRODUCTION ENGINEER"] ?? [])];
  }
  if (key.includes("MACHINE OPERATOR")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["MACHINE OPERATOR"] ?? [])];
  }
  if (key.includes("WELDER")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS.WELDER ?? ROLE_DEFAULT_MODULE_KEYS["WELDER HELPER"] ?? [])];
  }
  if (key.includes("BACK OFFICE")) {
    return [...(ROLE_DEFAULT_MODULE_KEYS["BACK OFFICE"] ?? [])];
  }
  return [];
}

/** Roles that bypass legacy leak cap (intentionally broad access). */
export const MODULE_LEAK_CAP_BYPASS_ROLES = new Set([
  "SUPERADMIN",
  "EA",
  "DIRECTOR",
  "ADMIN",
]);
