-- Add product fields to neworder table
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS item_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS item_code VARCHAR(100) DEFAULT NULL;
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS specification TEXT DEFAULT NULL;
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS quantity INT DEFAULT NULL;
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS unit VARCHAR(50) DEFAULT NULL;
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS price_per_unit DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS taxable_price DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS gst DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS total_price DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE neworder ADD COLUMN IF NOT EXISTS img_url VARCHAR(500) DEFAULT NULL;
