CREATE TABLE IF NOT EXISTS recurring_tasks (
  id INT NOT NULL AUTO_INCREMENT,
  task_title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  assigned_user_id INT NOT NULL,
  recurrence_type ENUM('daily','weekly','monthly','yearly') NOT NULL,
  repeat_interval INT NOT NULL DEFAULT 1,
  weekly_days JSON NULL,
  monthly_date INT NULL,
  yearly_month INT NULL,
  yearly_date INT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME NULL,
  due_date DATETIME NOT NULL,
  next_run_at DATETIME NOT NULL,
  last_generated_at DATETIME NULL,
  status ENUM('active','inactive') NOT NULL DEFAULT 'active',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by INT NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_recurring_tasks_assigned_user_id (assigned_user_id),
  KEY idx_recurring_tasks_status (status),
  KEY idx_recurring_tasks_next_run_at (next_run_at),
  KEY idx_recurring_tasks_recurrence_type (recurrence_type),
  KEY idx_recurring_tasks_created_by (created_by)
);
