-- MySQL: Create statements table
CREATE TABLE IF NOT EXISTS statements (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  trans_id VARCHAR(100) NOT NULL UNIQUE,
  date DATE NOT NULL,
  txn_dated_deb DATE NULL,
  cheq_no VARCHAR(100) NULL,
  description TEXT NULL,
  type ENUM('Credit', 'Debit') NOT NULL DEFAULT 'Credit',
  amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
  client_expense_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
