import dayjs from "dayjs";
import utc from "dayjs/plugin/utc";
import timezone from "dayjs/plugin/timezone";
import { getDbConnection } from "@/lib/db";

dayjs.extend(utc);
dayjs.extend(timezone);

class RecurrenceService {
  /**
   * datetime-local / MySQL strings are wall-clock times — store and compare as-is
   * (must match MySQL NOW() / session timezone, no IST offset shift).
   */
  parseSchedule(value) {
    if (!value) return null;
    const str = String(value).trim().replace(" ", "T").slice(0, 16);
    const d = dayjs(str);
    return d.isValid() ? d : null;
  }

  toMysqlDatetime(value) {
    if (!value) return null;
    const normalized = String(value).trim().replace("T", " ");
    if (normalized.length === 16) return `${normalized}:00`;
    return normalized.slice(0, 19);
  }

  nowMysql() {
    return dayjs();
  }

  /** After the manual first task: when is cron allowed to create the next one? */
  getNextRunAfterFirstTask(scheduledAt, config) {
    const scheduled = this.parseSchedule(scheduledAt);
    const now = this.nowMysql();

    if (scheduled?.isValid() && scheduled.isAfter(now, "minute")) {
      return this.toMysqlDatetime(scheduledAt);
    }

    return this.calculateNextDate({
      recurrence_type: config.recurrence_type,
      repeat_interval: config.repeat_interval,
      weekly_days: config.weekly_days,
      monthly_date: config.monthly_date,
      yearly_month: config.yearly_month,
      yearly_date: config.yearly_date,
      due_date: config.due_date || scheduledAt,
      next_run_at: scheduledAt,
      end_date: config.end_date,
    });
  }

  async ensureAutoGeneratedColumn(conn) {
    try {
      await conn.execute(
        `ALTER TABLE task ADD COLUMN is_auto_generated TINYINT(1) NOT NULL DEFAULT 0`
      );
      console.log("✅ Added task.is_auto_generated column");
    } catch (error) {
      if (error.errno !== 1060) throw error;
    }
  }

  /** Cron-created tasks: assign date + automatic flag for table "A" badge. */
  async backfillAutomaticTaskAssignDates(conn) {
    try {
      await this.ensureAutoGeneratedColumn(conn);

      const [dateResult] = await conn.execute(
        `UPDATE task
         SET followed_date = next_followup_date
         WHERE parent_recurring_task_id IS NOT NULL
           AND next_followup_date IS NOT NULL
           AND (
             followed_date IS NULL
             OR TRIM(IFNULL(CAST(followed_date AS CHAR), '')) = ''
             OR CAST(followed_date AS CHAR) LIKE '0000-00-00%'
           )`
      );
      if (dateResult.affectedRows > 0) {
        console.log(`✅ Backfilled assign date on ${dateResult.affectedRows} automatic task(s)`);
      }

      const [flagResult] = await conn.execute(
        `UPDATE task
         SET is_auto_generated = 1
         WHERE parent_recurring_task_id IS NOT NULL
           AND next_followup_date IS NOT NULL
           AND followed_date IS NOT NULL
           AND DATE(followed_date) = DATE(next_followup_date)
           AND TIME(followed_date) = TIME(next_followup_date)
           AND COALESCE(is_auto_generated, 0) = 0`
      );
      if (flagResult.affectedRows > 0) {
        console.log(`✅ Marked ${flagResult.affectedRows} task(s) as automatic (A)`);
      }
    } catch (error) {
      console.error("❌ Error backfilling automatic task fields:", error);
    }
  }

  async ensureUniqueTaskConstraint() {
    try {
      const conn = await getDbConnection();
      
      // Fix any existing tasks with null task_id
      const [tasksWithNullId] = await conn.execute(
        "SELECT * FROM task WHERE task_id IS NULL"
      );
      
      if (tasksWithNullId.length > 0) {
        console.log(`ℹ️ Found ${tasksWithNullId.length} tasks with null task_id, fixing...`);
        
        // Get current max task_id
        const [[{ max_id }]] = await conn.execute(
          "SELECT MAX(task_id) AS max_id FROM task"
        );
        let currentId = (max_id || 999);
        
        // Update each task with null task_id
        for (const task of tasksWithNullId) {
          currentId++;
          await conn.execute(
            "UPDATE task SET task_id = ? WHERE id = ?",
            [currentId, task.id]
          );
        }
        console.log(`✅ Fixed ${tasksWithNullId.length} tasks with null task_id`);
      }
      
      await conn.execute(`
        ALTER TABLE task 
        ADD CONSTRAINT uc_recurring_task_date 
        UNIQUE (parent_recurring_task_id, next_followup_date)
      `);
      console.log("✅ Added unique constraint for recurring tasks");
    } catch (error) {
      if (error.code === "ER_DUP_KEYNAME" || error.code === "ER_DUP_FIELDNAME") {
        console.log("ℹ️ Unique constraint already exists");
      } else {
        console.error("❌ Error adding unique constraint:", error);
      }
    }
  }
  /**
   * Calculate next run date based on recurrence configuration
   */
  calculateNextDate(config) {
    const {
      recurrence_type,
      repeat_interval = 1,
      weekly_days,
      monthly_date,
      yearly_month,
      yearly_date,
      due_date,
      next_run_at,
      end_date,
    } = config;

    const baseDate = this.parseSchedule(next_run_at || due_date);
    if (!baseDate?.isValid()) return null;
    let nextDate = null;

    switch (recurrence_type) {
      case "daily":
        nextDate = baseDate.add(repeat_interval, "day");
        break;

      case "weekly":
        nextDate = this.calculateNextWeeklyDate(baseDate, weekly_days, repeat_interval);
        break;

      case "monthly":
        nextDate = this.calculateNextMonthlyDate(baseDate, monthly_date, repeat_interval);
        break;

      case "yearly":
        nextDate = this.calculateNextYearlyDate(baseDate, yearly_month, yearly_date, repeat_interval);
        break;

      default:
        return null;
    }

    if (end_date && dayjs(nextDate).isAfter(dayjs(end_date))) {
      return null;
    }

    return nextDate ? nextDate.format("YYYY-MM-DD HH:mm:ss") : null;
  }

  calculateNextWeeklyDate(currentDate, weekly_days, repeat_interval = 1) {
    if (!weekly_days || weekly_days.length === 0) {
      return currentDate.add(7 * repeat_interval, "day");
    }

    const weekdayMap = {
      sunday: 0,
      monday: 1,
      tuesday: 2,
      wednesday: 3,
      thursday: 4,
      friday: 5,
      saturday: 6,
    };

    const currentDay = currentDate.day();
    const targetDays = weekly_days.map((day) => weekdayMap[day.toLowerCase()]).sort();

    let nextDay = targetDays.find((day) => day > currentDay);
    
    if (nextDay === undefined) {
      nextDay = targetDays[0];
      return currentDate.add(7 * repeat_interval, "day").day(nextDay);
    }

    return currentDate.add(nextDay - currentDay, "day");
  }

  calculateNextMonthlyDate(currentDate, monthly_date, repeat_interval = 1) {
    const targetDate = monthly_date || currentDate.date();
    let nextMonth = currentDate.add(repeat_interval, "month");

    const daysInMonth = nextMonth.daysInMonth();
    const adjustedDate = Math.min(targetDate, daysInMonth);

    return nextMonth.date(adjustedDate);
  }

  calculateNextYearlyDate(currentDate, yearly_month, yearly_date, repeat_interval = 1) {
    const targetMonth = yearly_month || currentDate.month() + 1;
    const targetDate = yearly_date || currentDate.date();
    
    let nextYear = currentDate.add(repeat_interval, "year");
    nextYear = nextYear.month(targetMonth - 1);
    
    const daysInMonth = nextYear.daysInMonth();
    const adjustedDate = Math.min(targetDate, daysInMonth);
    
    return nextYear.date(adjustedDate);
  }

  isTaskDue(task) {
    const now = this.nowMysql();
    const nextRunAt = this.parseSchedule(task.next_run_at);
    const endDate = task.end_date ? this.parseSchedule(task.end_date) : null;

    if (task.status !== "active" || !task.is_active) {
      return false;
    }

    if (!nextRunAt?.isValid()) {
      return false;
    }

    if (endDate?.isValid() && now.isAfter(endDate)) {
      return false;
    }

    return now.isAfter(nextRunAt) || now.isSame(nextRunAt, "minute");
  }

  async generateNextTask(recurringTask, conn) {
    const nextRunAt = this.calculateNextDate({
      recurrence_type: recurringTask.recurrence_type,
      repeat_interval: recurringTask.repeat_interval,
      weekly_days: recurringTask.weekly_days ? JSON.parse(recurringTask.weekly_days) : null,
      monthly_date: recurringTask.monthly_date,
      yearly_month: recurringTask.yearly_month,
      yearly_date: recurringTask.yearly_date,
      due_date: recurringTask.due_date,
      next_run_at: recurringTask.next_run_at,
      end_date: recurringTask.end_date,
    });

    if (!nextRunAt) {
      await conn.execute(
        `UPDATE recurring_tasks SET status = 'inactive', is_active = false WHERE id = ?`,
        [recurringTask.id]
      );
      return null;
    }

    // Calculate task_id same way as api/new-task/route.js
    const [[{ max_id }]] = await conn.execute(
      "SELECT MAX(task_id) AS max_id FROM task"
    );
    const task_id = (max_id || 999) + 1;
    console.log("🔍 Task ID calculation:", { max_id, task_id });

    // SAVE original next_run_at before updating!
    const originalNextRunAt = recurringTask.next_run_at;

    // FIRST CHECK IF TASK ALREADY EXISTS BEFORE TRYING TO INSERT!
    const [existingTasks] = await conn.execute(
      `SELECT id FROM task 
       WHERE parent_recurring_task_id = ? 
         AND DATE(next_followup_date) = DATE(?)
         AND TIME(next_followup_date) = TIME(?)`,
      [recurringTask.id, originalNextRunAt, originalNextRunAt]
    );

    if (existingTasks.length > 0) {
      console.log(`ℹ️ Task already exists for recurring task ${recurringTask.id}`);
      // Update next_run_at and last_generated_at even if task exists
      if (nextRunAt) {
        await conn.execute(
          `UPDATE recurring_tasks 
           SET next_run_at = ?, last_generated_at = NOW()
           WHERE id = ?`,
          [nextRunAt, recurringTask.id]
        );
      }
      return null;
    }

    // Get username from emplist using created_by empId
    const [[emp]] = await conn.execute(
      `SELECT username FROM emplist WHERE empId = ? LIMIT 1`,
      [recurringTask.created_by]
    );
    const creatorUsername = emp?.username || 'system';
    
    // Get assigned username from emplist or rep_list using assigned_user_id (empId)
    let assignedUsername = String(recurringTask.assigned_user_id);
    const [[assignedEmp]] = await conn.execute(
      `SELECT username FROM emplist WHERE empId = ? LIMIT 1`,
      [recurringTask.assigned_user_id]
    );
    if (assignedEmp?.username) {
      assignedUsername = assignedEmp.username;
    } else {
      const [[assignedRep]] = await conn.execute(
        `SELECT username FROM rep_list WHERE empId = ? LIMIT 1`,
        [recurringTask.assigned_user_id]
      );
      if (assignedRep?.username) assignedUsername = assignedRep.username;
    }

    console.log("🔍 Inserting task with values:", {
      task_id,
      task_title: recurringTask.task_title,
      description: recurringTask.description,
      assignedUsername,
      next_followup_date: originalNextRunAt,
      creatorUsername,
      parent_recurring_task_id: recurringTask.id
    });

    await this.ensureAutoGeneratedColumn(conn);

    try {
      await conn.execute(
        `INSERT INTO task (
          task_id, taskname, createdby, taskassignto, status, next_followup_date,
          followed_date, notes, visiting_card, task_video, task_prior, task_catg,
          parent_recurring_task_id, is_auto_generated
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)`,
        [
          task_id,
          recurringTask.task_title,
          creatorUsername,
          assignedUsername,
          "Pending",
          originalNextRunAt,
          originalNextRunAt,
          recurringTask.description,
          "",
          "",
          "Medium",
          "Software Development",
          recurringTask.id,
        ]
      );
    } catch (insertError) {
      console.error("❌ Error inserting task:", insertError);
      if (insertError.code === "ER_DUP_ENTRY") {
        // Duplicate task already exists
        console.log(`ℹ️ Task already exists for recurring task ${recurringTask.id}`);
        if (nextRunAt) {
          await conn.execute(
            `UPDATE recurring_tasks 
             SET next_run_at = ?, last_generated_at = NOW()
             WHERE id = ?`,
            [nextRunAt, recurringTask.id]
          );
        }
        return null;
      }
      throw insertError;
    }

    await conn.execute(
      `INSERT INTO task_followup (
        task_id, createdby, taskassignto, followed_date, notes, taskname, status, task_deadline
      )
      SELECT task_id, createdby, taskassignto, followed_date, notes, taskname, status, next_followup_date
      FROM task WHERE task_id = ?`,
      [task_id]
    );

    // NOW UPDATE next_run_at and last_generated_at!
    if (nextRunAt) {
      await conn.execute(
        `UPDATE recurring_tasks 
         SET next_run_at = ?, last_generated_at = NOW()
         WHERE id = ?`,
        [nextRunAt, recurringTask.id]
      );
    }

    console.log(`✅ Recurring task generated: Task ID ${task_id}, Recurring Task ID ${recurringTask.id}, Name: "${recurringTask.task_title}"`);

    return {
      task_id: task_id,
      parent_recurring_task_id: recurringTask.id,
      due_date: originalNextRunAt,
    };
  }

  validateRecurrenceConfig(data) {
    const errors = [];

    if (!data.recurrence_type || !["daily", "weekly", "monthly", "yearly"].includes(data.recurrence_type)) {
      errors.push("Valid recurrence_type is required (daily, weekly, monthly, yearly)");
    }

    if (!data.due_date) {
      errors.push("due_date is required");
    }

    if (!data.start_date) {
      errors.push("start_date is required");
    }

    if (data.due_date && data.start_date && dayjs(data.due_date).isBefore(dayjs(data.start_date))) {
      errors.push("due_date must be >= start_date");
    }

    if (data.recurrence_type === "weekly") {
      if (!data.weekly_days || !Array.isArray(data.weekly_days) || data.weekly_days.length === 0) {
        errors.push("weekly_days array is required for weekly recurrence");
      } else {
        const validDays = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"];
        const invalidDays = data.weekly_days.filter((day) => !validDays.includes(day.toLowerCase()));
        if (invalidDays.length > 0) {
          errors.push(`Invalid weekdays: ${invalidDays.join(", ")}`);
        }
      }
    }

    if (data.recurrence_type === "monthly") {
      if (!data.monthly_date || data.monthly_date < 1 || data.monthly_date > 31) {
        errors.push("monthly_date must be between 1 and 31");
      }
    }

    if (data.recurrence_type === "yearly") {
      if (!data.yearly_month || data.yearly_month < 1 || data.yearly_month > 12) {
        errors.push("yearly_month must be between 1 and 12");
      }
      if (!data.yearly_date || data.yearly_date < 1 || data.yearly_date > 31) {
        errors.push("yearly_date must be between 1 and 31");
      }
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }
}

export default new RecurrenceService();
